Bug 1904673 [wpt PR 46897] - serve: Fix exception in logger usage, a=testonly
Automatic update from web-platform-tests
serve: Fix exception in logger usage

The Logger.critical method doesn't take a file argument, at least in Python 3.12:

>>> import logging
>>> logging.getLogger().critical('test', file=None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.12/logging/__init__.py", line 1586, in critical
    self._log(CRITICAL, msg, args, **kwargs)
TypeError: Logger._log() got an unexpected keyword argument 'file'

--

wpt-commits: e4cf05764e3b0239593e2ccb4761d96a68a0efbc
wpt-pr: 46897