Bug 1911833 - Skip userScripts in GenerateWebIDLBindings.py r=rpl
Although the bindings generator skips MV2-only APIs at some point
(https://searchfox.org/mozilla-central/rev/1bc0601cc5b3d4c3919d220acbe248221ebce035/toolkit/components/extensions/webidl-api/GenerateWebIDLBindings.py#337-338),
that only happens after loading all schemas. Because user_scripts.json
contains multiple userScripts.register definitions (one for MV2 and one
for MV3), GenerateWebIDLBindings.py raised the following error before
this patch:

> TypeError: Unxpected multiple schema data for API property "userScripts.register" in schema group toolkit

This patch fixes the issue by ignoring the schemas that define the
userScripts API, and now the following test passes again:

```
./mach test toolkit/components/extensions/webidl-api/test/test_all_schemas_smoketest.py
```

Differential Revision: https://phabricator.services.mozilla.com/D227969